### ISSUE TITLE
think about c2

### ISSUE THREAD

**Issue by MatheMax** [kkmann/adoptr#129] opened 2019-02-22 16:36 UTC
Can c2() have negative values?
Should not be the case and if we are really sure we could use this as lower bound

**Comment by MatheMax** [comment] 2019-02-23 09:25
@kkmann if the validation works, we could also remove the option "c2_monotone". 
I think this was originally included to make things work, but I don't see why we need it anymore

**Comment by kkmann** [comment] 2019-02-23 10:42
true, sometimes additional constraints can help convergence due to better gradient information. But I highly doubt that that works with COBYLA. 
Happy to remove it. 
How do you feel about adding warnings for c2 < 0 or c2 non-monotone?

**Comment by MatheMax** [comment] 2019-02-26 09:54
For c2<0 it's a good idea
For non-monotone, I don't think so because I acutally don't believe that c2 has to be monotone in any situation

**Comment by kkmann** [comment] 2019-02-27 08:34
tentatively agreed, but I am having a hard time finding a situation in which it would not be monotone...

**Comment by MatheMax** [comment] 2019-02-27 09:11
I uploaded a file in our 'otsd-examples' package with such an example

**Comment by kkmann** [comment] 2019-02-27 16:57
hm, I am still skeptical - the problem u suggest is quite difficult to solve for us. I am almost certain that it is a numerical glitch. Did you look at the actual pivot values? I bet it looks quite different with 25 pivots. the s curve could be caused by the spline interpolation (do we need to revert that to linear?)!

**Comment by kkmann** [comment] 2019-02-27 16:58
@MatheMax  what's your rationale for this problem leading to non-monotone c2 (in theory?)

**Comment by MatheMax** [comment] 2019-02-28 12:20
c2_monotone is removed in #141

**Comment by kkmann** [comment] 2019-02-28 12:30
closing this now, repopen should we get into issues with c2 <  at some point

**Closed by kkmann** 2019-02-28 12:30 UTC
